### ISSUE TITLE
add contribution.md file

### ISSUE THREAD

**Issue by kiranrokkam09** [kiranrokkam09/Invoice_Management#1]
my repo doesn't have contribution file. I expect you to create me one.

**Comment by ad-astra-per-ardua** [comment]
Contribution process covers forking the repository, setting up the project locally, finding issues to work on, working on the issue in a separate branch, submitting a pull request, review process, and merging once approved. Would you like to add any more details or steps to this guide, or any other specific instructions for contributors?

**Comment by kiranrokkam09** [comment]
Hey @d982h8st7 sorry I will assign it to my friend

**Comment by Baburao-sanivada** [comment]
Hello @kiranrokkam09 i would love to work on this issue? I have the skills required to solve this issue
